Song search and validation improvement
GCCempt/GCC_OpenSong_bot pull request #76
Opened 2021-05-13 17:03 UTC by AllDayJon

- Search is now case in-sensitive
- Green success message on valid post
- Displays results for multiple incorrect songs at once

** Other **
- Created new "generate_link_dict()" function that creates a dictionary of all the urls on a page. 
The hyperlinked text is the key, and the URL is the value. This can be used to convert all the
keys to lowercase to perform a case insensitive search and return the url by referfencing the
value.

- Added docstring support for all modified functions during this commit.

2021-05-13 22:43 UTC, Infosecguy10 requested changes
We tested when the worship schedule is posted and the case insensitive match works well and returns that all songs are valid when the case doesn't match. However when the complete set is built, the links that are generated on the website within the set display do not work and the song itself fails to be inserted into the set on the website because the case doesn't match for the URL for that particular song.

When the validation is done, even as it returns that the songs are valid to the user on discord, it might need to replace the song names with the correct matching case in the songs.txt file so that the set displays correctly on the website. 

![image](https://user-images.githubusercontent.com/46640921/118196335-dc1d7700-b41a-11eb-86c8-07def6b212ae.png)

As shown, Jesus Paid It All inserts into the set correctly because the case matches while All Hail The Power Of Jesus Name and Is He Worthy do not insert correctly.

![image](https://user-images.githubusercontent.com/46640921/118196468-0f600600-b41b-11eb-9884-ebcbce5d69b2.png)

2021-05-14 03:04 UTC, AllDayJon commented on utils.py
> +def song_case_correction(song_file, song_list):
This function updates the text file with correct casing.

2021-05-14 03:06 UTC, AllDayJon commented
Update to auto-correct case in the text file.

https://github.com/GCCempt/GCC_OpenSong_bot/blob/4911f9f3718cecd6233d7eb58690c7e07ccfa770/utils.py#L192-L213

2021-05-14 07:24 UTC, dan4222 approved these changes

2021-05-14 07:25 UTC, merged